version: '3.8'

services:
  app:
    build: .
    container_name: my-blog-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://blog_user:blog_pass@postgres:5432/blog_db?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-secret
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./uploads:/app/uploads   # 文件上传持久化
      - ./src:/app/src           # 开发时可热更新（生产删除）
      - ./dist:/app/dist         # 同步构建产物（可选）
    command: ["node", "dist/index.js"]

  postgres:
    image: postgres:16-alpine
    ports:
       - "5432:5432"
    container_name: my-blog-postgres
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
      POSTGRES_DB: blog_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog_user -d blog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: my-blog-redis
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
